import {FormEvent,useState} from "react";
const services=[["01","Webs para negocios","Una presencia online profesional para que tus clientes te encuentren y contacten contigo."],["02","Diseño responsive","Tu web se adapta perfectamente a móvil, tablet y ordenador."],["03","Web rápida y moderna","Tecnología actual para ofrecer una experiencia fluida y profesional."],["04","Formularios de contacto","Recibe solicitudes y consultas directamente de tus clientes."],["05","SEO básico","Estructura y contenidos preparados para que Google pueda entender tu negocio."],["06","Publicación y mantenimiento","Te ayudo a poner tu web online y a mantenerla actualizada."]];
const types=["Restaurante","Comercio","Profesional / autónomo","Peluquería / estética","Empresa","Otro"];
export default function App(){const[sent,setSent]=useState(false);const[loading,setLoading]=useState(false);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);const f=e.currentTarget,d=Object.fromEntries(new FormData(f).entries());try{const r=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});if(!r.ok)throw Error();setSent(true);f.reset()}catch{alert("No se ha podido enviar. Escríbeme directamente por email.")}finally{setLoading(false)}}
return <main><nav className="nav"><a className="brand" href="#inicio"><span>N</span>NexoSites</a><div className="navlinks"><a href="#servicios">Servicios</a><a href="#proceso">Cómo trabajo</a><a href="#contacto" className="navcta">Pedir presupuesto</a></div></nav>
<section id="inicio" className="hero"><div><p className="eyebrow">DISEÑO WEB PARA NEGOCIOS</p><h1>Tu negocio merece una web <em>que funcione.</em></h1><p className="lead">Creo páginas web modernas, rápidas y adaptadas a móviles para ayudarte a mostrar tu negocio y conseguir nuevos clientes.</p><div className="actions"><a className="button primary" href="#contacto">Cuéntame tu idea <span>→</span></a><a className="button ghost" href="#servicios">Ver servicios</a></div><div className="trust">✓ Diseño personalizado　✓ Responsive　✓ Sin permanencias</div></div>
<div className="hero-card"><div className="browser"><div className="dots"><i/><i/><i/></div><div className="screen"><div className="mini-logo">N</div><div className="screen-title">Tu negocio,<br/><strong>online.</strong></div><div className="screen-line"/><div className="screen-line short"/><div className="screen-button">Contactar</div></div></div><div className="phone"><div className="phone-top"/><div className="phone-content"><b>NexoSites</b><span>Tu web, en cualquier pantalla.</span><small>DESCUBRIR →</small></div></div></div></section>
<section id="servicios" className="section"><div className="section-head"><p className="eyebrow">LO QUE PUEDO HACER POR TI</p><h2>Una web pensada para tu negocio.</h2><p>No necesitas una web complicada. Necesitas una web clara, profesional y que facilite que tus clientes contacten contigo.</p></div><div className="service-grid">{services.map(([n,t,d])=><article className="service" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="audience"><div><p className="eyebrow">PARA QUIÉN</p><h2>Si tienes un negocio,<br/>podemos crear tu web.</h2></div><div className="pills">{types.map(t=><span key={t}>{t}</span>)}</div></section>
<section id="proceso" className="section"><div className="section-head"><p className="eyebrow">EL PROCESO</p><h2>De tu idea a Internet.</h2></div><div className="steps">{[["01","Me cuentas tu idea","Rellenas el formulario y me explicas qué necesitas."],["02","Preparamos la propuesta","Te explico qué haría, cuánto cuesta y los plazos."],["03","Creo tu web","Diseño y desarrollo una web adaptada a tu negocio."],["04","La ponemos online","Publicamos tu web y te dejo todo preparado."]].map(([n,t,d])=><div key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section id="contacto" className="contact"><div className="contact-copy"><p className="eyebrow">HABLEMOS</p><h2>Cuéntame qué tienes en mente.</h2><p>No necesitas tenerlo todo decidido. Explícame tu negocio y la idea que tienes para tu web. Te responderé con una propuesta.</p><div className="email">✉ dcuencadelrio@gmail.com</div></div><div className="form-wrap">{sent?<div className="success"><div>✓</div><h3>¡Solicitud enviada!</h3><p>He recibido tu idea. Te contactaré lo antes posible.</p><button className="button primary" onClick={()=>setSent(false)}>Enviar otra solicitud</button></div>:<form onSubmit={submit}><input name="website" className="honeypot" tabIndex={-1} autoComplete="off"/><label>Nombre<input required name="name" placeholder="Tu nombre"/></label><div className="two"><label>Email<input required type="email" name="email" placeholder="tu@email.com"/></label><label>Teléfono<input name="phone" placeholder="Opcional"/></label></div><label>Tipo de negocio<select name="business"><option value="">Selecciona una opción</option>{types.map(t=><option key={t}>{t}</option>)}</select></label><label>Presupuesto aproximado<select name="budget"><option>Prefiero hablarlo</option><option>Menos de 500 €</option><option>500 – 1.000 €</option><option>1.000 – 2.000 €</option><option>Más de 2.000 €</option></select></label><label>Cuéntame tu idea<textarea required name="message" rows={5} placeholder="¿Qué tipo de web necesitas? ¿Qué quieres que pueda hacer?"/></label><button disabled={loading} className="button primary submit">{loading?"Enviando...":"Solicitar presupuesto →"}</button></form>}</div></section>
<footer><div className="brand"><span>N</span>NexoSites</div><p>Webs modernas para negocios que quieren crecer.</p><small>© 2026 NexoSites</small></footer></main>}